# Generated by Django 4.2.4 on 2023-12-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('totalElevation', models.FloatField()),
                ('highestPoint', models.FloatField()),
                ('type', models.CharField(max_length=25)),
                ('duration', models.TimeField()),
                ('country', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('distance', models.IntegerField()),
                ('imageFile', models.CharField(max_length=100)),
                ('altitude', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clientSecret', models.CharField(max_length=300)),
                ('refreshSecret', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAchieved', models.DateField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='BestEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=25)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.user'),
        ),
    ]
