# Generated by Django 4.2.4 on 2023-12-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullName',
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='dsa', max_length=100),
            preserve_default=False,
        ),
    ]
