# Generated by Django 4.2.4 on 2023-12-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_milestone_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
