# Generated by Django 4.2.4 on 2023-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_trophy_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
