# Generated by Django 4.2.4 on 2023-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_trophy_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermilestone',
            name='dateAchieved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
