# Generated by Django 4.2.4 on 2023-12-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='besteffort',
            name='time',
            field=models.DurationField(),
        ),
    ]
