# Generated by Django 4.2.4 on 2023-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_activity_duration_alter_besteffort_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='besteffort',
            name='time',
            field=models.TimeField(),
        ),
    ]
