# Generated by Django 4.2.4 on 2023-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_rename_refreshsecret_user_refreshtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiresAt',
            field=models.IntegerField(),
        ),
    ]
