# Generated by Django 4.2.4 on 2024-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_user_expiresat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clientID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clientSecret',
        ),
        migrations.AddField(
            model_name='user',
            name='strava_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
