# Generated by Django 4.2.4 on 2024-05-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_user_clientid_remove_user_clientsecret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullName',
        ),
    ]
