# Generated by Django 4.2.4 on 2024-05-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_user_webuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='webuser_id',
            new_name='webuser',
        ),
    ]
