# Generated by Django 6.0.1 on 2026-02-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_rename_webuser_id_user_webuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='stravaID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='strava_id',
            field=models.BigIntegerField(),
        ),
    ]
